name: Build on commit to main branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: sesamci
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build . -t sesam/sesam-bigquery:latest
      - name: Push docker image
        run: docker push sesam/sesam-bigquery:latest 
